
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.io.File;
import java.util.Arrays;
import java.util.Comparator;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * this is the main class of sorting program 
 * @author Hafsa Umar
 */
public class Sorting extends javax.swing.JFrame {

    /**
     * Creates new form Sorting
     */
    private File[] files;

    /**
     * in the constructor of main class, Abstract file menu has been added to open a file and exit the program
     * Open menu , opens a file and displays the images selected to the scroll panel. 
     * There are four sort options at the top of the form to sort by names and size of the images.
     */
    
    public Sorting() {
        initComponents();
        fileMenu.add(new AbstractAction("Open") {
            @Override
            public void actionPerformed(ActionEvent e) {
                JFileChooser openFile = new JFileChooser();
                openFile.setMultiSelectionEnabled(true);
                int r = openFile.showDialog(null, JFileChooser.APPROVE_SELECTION);
                if (r == JFileChooser.APPROVE_OPTION) {
                    files = openFile.getSelectedFiles();
                    displayImages(files);                    
                }
            }
        });
        fileMenu.add(new AbstractAction("Exit") {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });
    }

    private void displayImages(File[] files) {
        JPanel panel = new JPanel(new GridLayout(files.length, 1));
        for (int lop = 0; lop < files.length; lop++) {
            ImageIcon icon = new ImageIcon(files[lop].getAbsolutePath());
            JLabel label = new JLabel(icon);
            panel.add(label);
        }
        jScrollPane1.setViewportView(panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameAsort = new javax.swing.JRadioButton();
        nameDSort = new javax.swing.JRadioButton();
        sizeASort = new javax.swing.JRadioButton();
        sizeDSort = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sort By:");

        buttonGroup1.add(nameAsort);
        nameAsort.setSelected(true);
        nameAsort.setText("Name(A)");
        nameAsort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameAsortActionPerformed(evt);
            }
        });

        buttonGroup1.add(nameDSort);
        nameDSort.setText("Name(D)");
        nameDSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameDSortActionPerformed(evt);
            }
        });

        buttonGroup1.add(sizeASort);
        sizeASort.setText("Size(A)");
        sizeASort.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sizeASort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeASortActionPerformed(evt);
            }
        });

        buttonGroup1.add(sizeDSort);
        sizeDSort.setText("Size(D)");
        sizeDSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeDSortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameAsort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameDSort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sizeASort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sizeDSort)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameAsort)
                    .addComponent(nameDSort)
                    .addComponent(sizeASort)
                    .addComponent(sizeDSort))
                .addContainerGap())
        );

        jScrollPane1.setName("scrollPanel"); // NOI18N

        fileMenu.setText("File");
        jMenuBar1.add(fileMenu);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameAsortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameAsortActionPerformed
        Arrays.sort(files, new Comparator<File>(){
            @Override
            public int compare(File o1, File o2) {
                return o1.getName().compareTo(o2.getName());
            }
        });
        displayImages(files);
        
    }//GEN-LAST:event_nameAsortActionPerformed

    private void nameDSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameDSortActionPerformed
        // TODO add your handling code here:
        Arrays.sort(files, new Comparator<File>(){
            @Override
            public int compare(File o1, File o2) {
                return o1.getName().compareTo(o2.getName())*(-1);
            }
        });
        displayImages(files);
    }//GEN-LAST:event_nameDSortActionPerformed

    private void sizeASortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeASortActionPerformed
        // TODO add your handling code here:
        Arrays.sort(files, new Comparator<File>(){
            @Override
            public int compare(File o1, File o2) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                return (int)(o1.length()- o2.length());
            }
        });
        displayImages(files); 
    }//GEN-LAST:event_sizeASortActionPerformed

    private void sizeDSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeDSortActionPerformed
        // TODO add your handling code here:
        Arrays.sort(files, new Comparator<File>(){
            @Override
            public int compare(File o1, File o2) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                return (int)((o1.length()- o2.length())*(-1));
            }
        });
        displayImages(files);
    }//GEN-LAST:event_sizeDSortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sorting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sorting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sorting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sorting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sorting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton nameAsort;
    private javax.swing.JRadioButton nameDSort;
    private javax.swing.JRadioButton sizeASort;
    private javax.swing.JRadioButton sizeDSort;
    // End of variables declaration//GEN-END:variables
}
