/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fi.uta;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Hafsa Umar
 */
public class Houses extends javax.swing.JFrame {

    /**
     * Creates new form Houses
     */
    public Houses() {
        initComponents();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        chooseImage = new javax.swing.JMenuItem();
        addCaption = new javax.swing.JMenuItem();
        houseGraphics1 = new fi.uta.HouseGraphics();

        chooseImage.setText("Change Background");
        chooseImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chooseImageMouseClicked(evt);
            }
        });
        chooseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseImageActionPerformed(evt);
            }
        });
        jPopupMenu1.add(chooseImage);

        addCaption.setText("Add Caption");
        addCaption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCaptionActionPerformed(evt);
            }
        });
        jPopupMenu1.add(addCaption);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        houseGraphics1.setComponentPopupMenu(jPopupMenu1);

        javax.swing.GroupLayout houseGraphics1Layout = new javax.swing.GroupLayout(houseGraphics1);
        houseGraphics1.setLayout(houseGraphics1Layout);
        houseGraphics1Layout.setHorizontalGroup(
            houseGraphics1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 727, Short.MAX_VALUE)
        );
        houseGraphics1Layout.setVerticalGroup(
            houseGraphics1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(houseGraphics1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(houseGraphics1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseImageActionPerformed
        JFileChooser openFile = new JFileChooser();
        int r = openFile.showDialog(null, JFileChooser.APPROVE_SELECTION);
        if (r == JFileChooser.APPROVE_OPTION) {
            String sname = openFile.getName();
            JLabel image = new JLabel("", new ImageIcon(sname), JLabel.CENTER);
            houseGraphics1.add(image, BorderLayout.CENTER);
            try {
                houseGraphics1.setImage(ImageIO.read(openFile.getSelectedFile()));//read(openFile.getSelectedFile().getAbsolutePath()));//Visible(true);
            } catch (IOException ex) {
                Logger.getLogger(Houses.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_chooseImageActionPerformed

    private void chooseImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chooseImageMouseClicked
       
    }//GEN-LAST:event_chooseImageMouseClicked

    private void addCaptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCaptionActionPerformed
        String  captionLine = JOptionPane.showInputDialog(this, "Please Enter Caption","Input", JOptionPane.OK_OPTION);
        houseGraphics1.setCaption(captionLine);
    }//GEN-LAST:event_addCaptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Houses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Houses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Houses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Houses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Houses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addCaption;
    private javax.swing.JMenuItem chooseImage;
    private fi.uta.HouseGraphics houseGraphics1;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
