
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Hafsa Umar
 */
public class Information extends javax.swing.JFrame {

    /**
     * Creates new form Information
     */
    public Information() {
        initComponents();
        analysisMenu.setVisible(false);
    }
    private List<Person> people;
    private int peopleSize;
    private int current;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fnameTextbox = new javax.swing.JTextField();
        lnameTextbox = new javax.swing.JTextField();
        btownTextbox = new javax.swing.JTextField();
        byearTextbox = new javax.swing.JTextField();
        fnameEditButton = new javax.swing.JButton();
        lnameEditButton = new javax.swing.JButton();
        btownEditButton = new javax.swing.JButton();
        byearEditButton = new javax.swing.JButton();
        mstatusLabel = new javax.swing.JLabel();
        mstatusTextbox = new javax.swing.JTextField();
        mstatusAddButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ldataMenu = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        nextMenu = new javax.swing.JMenuItem();
        prevMenu = new javax.swing.JMenuItem();
        analysisMenu = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("First Name");

        jLabel2.setText("Last Name");

        jLabel3.setText("Birth Town");

        jLabel4.setText("Birth Year");

        fnameTextbox.setEditable(false);
        fnameTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameTextboxActionPerformed(evt);
            }
        });

        lnameTextbox.setEditable(false);

        btownTextbox.setEditable(false);
        btownTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btownTextboxActionPerformed(evt);
            }
        });

        byearTextbox.setEditable(false);

        fnameEditButton.setText("Edit");
        fnameEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameEditButtonActionPerformed(evt);
            }
        });

        lnameEditButton.setText("Edit");
        lnameEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameEditButtonActionPerformed(evt);
            }
        });

        btownEditButton.setText("Edit");
        btownEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btownEditButtonActionPerformed(evt);
            }
        });

        byearEditButton.setText("Edit");
        byearEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byearEditButtonActionPerformed(evt);
            }
        });

        mstatusLabel.setText("Marital Status");
        mstatusLabel.setOpaque(true);

        mstatusTextbox.setEditable(false);

        mstatusAddButton.setText("Edit");
        mstatusAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mstatusAddButtonActionPerformed(evt);
            }
        });

        jMenu1.setMnemonic('f');
        jMenu1.setText("File");

        ldataMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        ldataMenu.setText("Load Data(EX2.2)");
        ldataMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ldataMenuActionPerformed(evt);
            }
        });
        jMenu1.add(ldataMenu);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Load Population(EX2.3)");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem7.setText("Generate(EX2.4)");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Exit(EX2.1)");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('v');
        jMenu2.setText("View");

        nextMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        nextMenu.setText("Next");
        nextMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextMenuActionPerformed(evt);
            }
        });
        jMenu2.add(nextMenu);

        prevMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        prevMenu.setText("Previous");
        prevMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevMenuActionPerformed(evt);
            }
        });
        jMenu2.add(prevMenu);

        jMenuBar1.add(jMenu2);

        analysisMenu.setMnemonic('a');
        analysisMenu.setText("Analysis");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("First Name Stats");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        analysisMenu.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Last Name Stats");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        analysisMenu.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Birth Town Stats");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        analysisMenu.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Birth Year Stats");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        analysisMenu.add(jMenuItem6);

        jMenuBar1.add(analysisMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mstatusLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mstatusTextbox, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fnameTextbox)
                            .addComponent(lnameTextbox)
                            .addComponent(btownTextbox)
                            .addComponent(byearTextbox, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lnameEditButton)
                    .addComponent(fnameEditButton)
                    .addComponent(btownEditButton)
                    .addComponent(byearEditButton)
                    .addComponent(mstatusAddButton))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fnameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnameEditButton))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lnameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnameEditButton))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btownTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btownEditButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(byearTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(byearEditButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mstatusLabel)
                    .addComponent(mstatusTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mstatusAddButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnameTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameTextboxActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_fnameTextboxActionPerformed

    private void btownTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btownTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btownTextboxActionPerformed

    private void ldataMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ldataMenuActionPerformed

        initializeFileData();
        displayNextRowData();
        analysisMenu.setVisible(true);
    }//GEN-LAST:event_ldataMenuActionPerformed

    private void initializeFileData() {
        String fileName = "people.txt";
        people = Person.loadPersons(fileName);
        System.out.println("Loading persons from file " + fileName);
        System.out.println(people.size());
        people.forEach((p) -> {
            System.out.println(p);
        });
        peopleSize = people.size();
        current = -1;
    }

    private void displayNextRowData() {
        if (current != (peopleSize - 1)) {
            current++;
            fnameTextbox.setText(people.get(current).getFirstName());
            lnameTextbox.setText(people.get(current).getLastName());
            byearTextbox.setText(String.valueOf(people.get(current).getBirthYear()));
            btownTextbox.setText(people.get(current).getBirthTown());
            mstatusTextbox.setText(String.valueOf(people.get(current).getMaritalStatus()));
        } else {
            JOptionPane.showMessageDialog(this, "No more people, Load Again to Continue", "Stop", JOptionPane.CANCEL_OPTION);
        }
    }

    private void displayPreviousRowData() {
        if (current > 0 && current < peopleSize) {
            current--;
            fnameTextbox.setText(people.get(current).getFirstName());
            lnameTextbox.setText(people.get(current).getLastName());
            byearTextbox.setText(String.valueOf(people.get(current).getBirthYear()));
            btownTextbox.setText(people.get(current).getBirthTown());
            mstatusTextbox.setText(String.valueOf(people.get(current).getMaritalStatus()));
        } else {
            JOptionPane.showMessageDialog(this, "No more people, Load Again to Continue", "Stop", JOptionPane.CANCEL_OPTION);
        }
    }

    private void nextMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextMenuActionPerformed
        displayNextRowData();
    }//GEN-LAST:event_nextMenuActionPerformed


    private void prevMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevMenuActionPerformed
        displayPreviousRowData();
    }//GEN-LAST:event_prevMenuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        closingFormConfirmation();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    private void closingFormConfirmation() {
        int exitOption = JOptionPane.showConfirmDialog(this, "You will Loose all the updated Data! Are you sure you want to Exit?", "Sure?", JOptionPane.YES_NO_OPTION);
        if (exitOption == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }

    private void fnameEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameEditButtonActionPerformed
        String firstName = JOptionPane.showInputDialog(this, "Please input First Name", "Edit", JOptionPane.OK_CANCEL_OPTION);
        people.get(current).setFirstName(firstName);
        fnameTextbox.setText(firstName);
    }//GEN-LAST:event_fnameEditButtonActionPerformed

    private void lnameEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameEditButtonActionPerformed
        String lastName = JOptionPane.showInputDialog(this, "Please input Last Name", "Edit", JOptionPane.OK_CANCEL_OPTION);
        people.get(current).setLastName(lastName);
        lnameTextbox.setText(lastName);
    }//GEN-LAST:event_lnameEditButtonActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Population pop = new Population("Canada");
        people = new LinkedList<Person>();
        for (int i = 0; i < 6; i++) {
            people.add(pop.nextPerson());
        }
        peopleSize = people.size();
        current = -1;
        displayNextRowData();
        analysisMenu.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btownEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btownEditButtonActionPerformed
        String birthTown = JOptionPane.showInputDialog(this, "Please input Birth Town", "Edit", JOptionPane.OK_CANCEL_OPTION);
        people.get(current).setBirthTown(birthTown);
        btownTextbox.setText(birthTown);
    }//GEN-LAST:event_btownEditButtonActionPerformed

    private void byearEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byearEditButtonActionPerformed
        try {
            String birthYear = JOptionPane.showInputDialog(this, "Please input Birth Year", "Edit", JOptionPane.OK_CANCEL_OPTION);
            people.get(current).setBirthYear(Integer.parseInt(birthYear));
            byearTextbox.setText(birthYear);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please Enter valid Year", "Error", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_byearEditButtonActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        String inputNumber = JOptionPane.showInputDialog(this, "Enter the number of People to Generate", "Input", JOptionPane.OK_CANCEL_OPTION);
        peopleSize = Integer.parseInt(inputNumber);
        Population pop = new Population("Canada");
        people = new LinkedList<Person>();
        for (int i = 0; i < peopleSize; i++) {
            people.add(pop.nextPerson());
        }
        current = -1;
        System.out.println(people.size());
        displayNextRowData();
        analysisMenu.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        closingFormConfirmation();
    }//GEN-LAST:event_formWindowClosing

    private void mstatusAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mstatusAddButtonActionPerformed
        String maritalStatus = String.valueOf(JOptionPane.showInputDialog(this, "Please Enter Marital Status", "Input", JOptionPane.QUESTION_MESSAGE, null, Person.MaritalStatus.values(), Person.MaritalStatus.SINGLE));
        mstatusTextbox.setText(String.valueOf(Person.MaritalStatus.valueOf(maritalStatus)));
        people.get(current).setMaritalStatus(Person.MaritalStatus.valueOf(maritalStatus));
    }//GEN-LAST:event_mstatusAddButtonActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        Collections.sort(people, new Comparator<Person>() {
            @Override
            public int compare(Person o1, Person o2) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                return o1.getBirthYear() - o2.getBirthYear();
            }
            //return 0; //To change body of generated lambdas, choose Tools | Templates.
        });
        for (int i = 0; i < people.size(); i++) {
            System.out.println(people.get(i).getBirthYear());
        }
        int sumforAverage = 0;
        for (int i = 0; i < people.size(); i++) {
            sumforAverage += people.get(i).getBirthYear();
        }
        int yearAverage = sumforAverage / people.size();
        JOptionPane.showMessageDialog(this, "Minimum = " + String.valueOf(people.get(0).getBirthYear()) + " Maximum = " + String.valueOf(people.get(people.size() - 1).getBirthYear()) + " Average = " + String.valueOf(yearAverage), "Birth Year Statistics", JOptionPane.OK_OPTION);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

        List<String> dummy = new ArrayList<>();
        for (int i = 0; i < people.size(); i++) {
            dummy.add(people.get(i).getBirthTown());
        }
        Set<String> uniqueYear = new HashSet<String>(dummy);
        System.out.println(uniqueYear.toString());
        JOptionPane.showMessageDialog(this, "Unique Towns Are  = " + uniqueYear.toString(), "Birth Town Statistics", JOptionPane.OK_OPTION);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        List<String> dummy = new ArrayList<>();
        for (int i = 0; i < people.size(); i++) {
            dummy.add(people.get(i).getFirstName());
        }
        Set<String> uniqueFName = new HashSet<String>(dummy);
        System.out.println(uniqueFName.toString());
        JOptionPane.showMessageDialog(this, "Unique First Names Are  = " + uniqueFName.toString(), "First Name Statistics", JOptionPane.OK_OPTION);
   
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
            List<String> dummy = new ArrayList<>();
        for (int i = 0; i < people.size(); i++) {
            dummy.add(people.get(i).getLastName());
        }
        Set<String> uniqueLName = new HashSet<String>(dummy);
        System.out.println(uniqueLName.toString());
        JOptionPane.showMessageDialog(this, "Unique Last Names Are  = " + uniqueLName.toString(), "Last Name Statistics", JOptionPane.OK_OPTION);
   
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Information().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu analysisMenu;
    private javax.swing.JButton btownEditButton;
    private javax.swing.JTextField btownTextbox;
    private javax.swing.JButton byearEditButton;
    private javax.swing.JTextField byearTextbox;
    private javax.swing.JButton fnameEditButton;
    private javax.swing.JTextField fnameTextbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem ldataMenu;
    private javax.swing.JButton lnameEditButton;
    private javax.swing.JTextField lnameTextbox;
    private javax.swing.JButton mstatusAddButton;
    private javax.swing.JLabel mstatusLabel;
    private javax.swing.JTextField mstatusTextbox;
    private javax.swing.JMenuItem nextMenu;
    private javax.swing.JMenuItem prevMenu;
    // End of variables declaration//GEN-END:variables
}
