/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ex1.pkg3;

/**
 *
 * @author Hafsa Umar
 */
public class MouseListener extends javax.swing.JFrame {

    /**
     * Creates new form MouseListener
     */
    public MouseListener() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mouseClickedTextbox = new javax.swing.JTextField();
        mouseMoveTextbox = new javax.swing.JTextField();
        mouseWheeltextbox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                formMouseWheelMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        mouseClickedTextbox.setText("Mouse Clicked ");
        mouseClickedTextbox.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mouseClickedTextboxMouseMoved(evt);
            }
        });
        mouseClickedTextbox.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                mouseClickedTextboxMouseWheelMoved(evt);
            }
        });
        mouseClickedTextbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseClickedTextboxMouseClicked(evt);
            }
        });

        mouseMoveTextbox.setText("Mouse Movement");
        mouseMoveTextbox.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mouseMoveTextboxMouseMoved(evt);
            }
        });
        mouseMoveTextbox.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                mouseMoveTextboxMouseWheelMoved(evt);
            }
        });
        mouseMoveTextbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseMoveTextboxMouseClicked(evt);
            }
        });

        mouseWheeltextbox.setText("Mouse Wheel");
        mouseWheeltextbox.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mouseWheeltextboxMouseMoved(evt);
            }
        });
        mouseWheeltextbox.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                mouseWheeltextboxMouseWheelMoved(evt);
            }
        });
        mouseWheeltextbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseWheeltextboxMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mouseClickedTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mouseMoveTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mouseWheeltextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(mouseClickedTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(mouseMoveTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(mouseWheeltextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mouseClickedTextboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClickedTextboxMouseClicked
        // TODO add your handling code here:
        mouseClickedTextbox.setText("Mouse was Clicked: on Textbox1");
    }//GEN-LAST:event_mouseClickedTextboxMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        mouseClickedTextbox.setText("Mouse was Clicked: on Form");
    }//GEN-LAST:event_formMouseClicked

    private void mouseMoveTextboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseMoveTextboxMouseClicked
        // TODO add your handling code here:
        mouseClickedTextbox.setText("Mouse was Clicked: on Textbox2");
    }//GEN-LAST:event_mouseMoveTextboxMouseClicked

    private void mouseWheeltextboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseWheeltextboxMouseClicked
        // TODO add your handling code here:
        mouseClickedTextbox.setText("Mouse was Clicked: on Textbox3");
    }//GEN-LAST:event_mouseWheeltextboxMouseClicked

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        mouseMoveTextbox.setText("Move Moved: on Form X = "+ getMousePosition().x + " Y = " + getMousePosition().y);
    }//GEN-LAST:event_formMouseMoved

    private void mouseClickedTextboxMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClickedTextboxMouseMoved
        // TODO add your handling code here:
         mouseMoveTextbox.setText("Move Moved: on Textbox1 X = "+ getMousePosition().x + " Y = " + getMousePosition().y);
    }//GEN-LAST:event_mouseClickedTextboxMouseMoved

    private void mouseMoveTextboxMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseMoveTextboxMouseMoved
        // TODO add your handling code here:
         mouseMoveTextbox.setText("Move Moved: on Textbox2 X = "+ getMousePosition().x + " Y = " + getMousePosition().y);
    }//GEN-LAST:event_mouseMoveTextboxMouseMoved

    private void mouseWheeltextboxMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseWheeltextboxMouseMoved
        // TODO add your handling code here:
         mouseMoveTextbox.setText("Move Moved: on Textbox3 X = "+ getMousePosition().x + " Y = " + getMousePosition().y);
    }//GEN-LAST:event_mouseWheeltextboxMouseMoved

    private void formMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_formMouseWheelMoved
        // TODO add your handling code here:
        mouseWheeltextbox.setText("Mouse Wheel Moved on Form");
    }//GEN-LAST:event_formMouseWheelMoved

    private void mouseClickedTextboxMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_mouseClickedTextboxMouseWheelMoved
        // TODO add your handling code here:
        mouseWheeltextbox.setText("Mouse Wheel Moved on Textbox 1");
    }//GEN-LAST:event_mouseClickedTextboxMouseWheelMoved

    private void mouseMoveTextboxMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_mouseMoveTextboxMouseWheelMoved
        // TODO add your handling code here:
        mouseWheeltextbox.setText("Mouse Wheel Moved on Textbox 2");
    }//GEN-LAST:event_mouseMoveTextboxMouseWheelMoved

    private void mouseWheeltextboxMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_mouseWheeltextboxMouseWheelMoved
        // TODO add your handling code here:
        mouseWheeltextbox.setText("Mouse Wheel Moved on Textbox 3");
    }//GEN-LAST:event_mouseWheeltextboxMouseWheelMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MouseListener.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MouseListener.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MouseListener.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MouseListener.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MouseListener().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField mouseClickedTextbox;
    private javax.swing.JTextField mouseMoveTextbox;
    private javax.swing.JTextField mouseWheeltextbox;
    // End of variables declaration//GEN-END:variables
}
