
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JPanel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.NumberFormat;
import java.util.Currency;
import java.util.ResourceBundle;
import javax.swing.Box;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Hafsa Umar
 */
public class DateTime extends javax.swing.JFrame {

    /**
     * Creates new form DateTime
     */
    public DateTime() {
        initComponents();
        dateFormat = DateFormat.getDateInstance(DateFormat.FULL, Locale.UK);
        timeFormat = DateFormat.getTimeInstance(DateFormat.FULL, Locale.UK);
        updateLabels();
        setBackgroundTranslucent();
        setSystemTray();        
        setComboBox();
    }

    private void setComboBox() {
        ///combobox settings
        Locale[] locales = Locale.getAvailableLocales();
        localeCombobox = new JComboBox(locales);
        for (int i = 0;i<locales.length;i++){
            localeCombobox.addItem(locales[i].toString());
        }
        localeCombobox.setRenderer(new LocaleRenderer(Locale.US));
        localeCombobox.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                Locale l = (Locale) localeCombobox.getSelectedItem();
                updateLocaleSpecifics(l);
                updateLabels();
                localeCombobox.setRenderer(new LocaleRenderer(l));
            }
        });
        localeCombobox.repaint();
    }

    private void setSystemTray() {
        ////Seting System tray
        if (SystemTray.isSupported()) {
            // System tray is there already, get access to related object
            SystemTray tray = SystemTray.getSystemTray();
            try {
                // Tray contains icons, which are TrayIcon objects
                tray.add(new WeekTrayIcon(this));
            } catch (AWTException ex) {
            }
        }
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        pack();
        setVisible(true);
    }

    private void setBackgroundTranslucent() throws HeadlessException {
        ////Setting Transparent Background
        boolean uniformTranslucencySupport = false;
        if (!isUndecorated()) {
            System.out.println("is Indecorated");
            // setUndecorated(true);
        }
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gd = ge.getDefaultScreenDevice();
        
        uniformTranslucencySupport = gd.isWindowTranslucencySupported(GraphicsDevice.WindowTranslucency.TRANSLUCENT);
        
        if (uniformTranslucencySupport) {
            //setBackground(new Color(200, 200, 200, 128));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transparencyPanel1 = new TransparencyPanel();
        dateLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        localeCombobox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dateLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        dateLabel.setText("jLabel1");

        timeLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        timeLabel.setText("jLabel1");

        javax.swing.GroupLayout transparencyPanel1Layout = new javax.swing.GroupLayout(transparencyPanel1);
        transparencyPanel1.setLayout(transparencyPanel1Layout);
        transparencyPanel1Layout.setHorizontalGroup(
            transparencyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transparencyPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transparencyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeLabel)
                    .addComponent(dateLabel))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        transparencyPanel1Layout.setVerticalGroup(
            transparencyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transparencyPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(timeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(dateLabel)
                .addGap(46, 46, 46))
        );

        localeCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localeComboboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transparencyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(localeCombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(localeCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transparencyPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void localeComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localeComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localeComboboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DateTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DateTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DateTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DateTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DateTime().setVisible(true);
            }
        });
    }

    public void updateLabels() {
        // Present the texts using the current locale,
        // String from the resource bundle, numbers formatted
        String time = timeFormat.format(new Date());
        dateLabel.setText(dateFormat.format(new Date()));
       // String time = dateFormat.format(new Date());
        timeLabel.setText(time);
    }

    /**
     * This method updates the objects used to present information.
     */
    public void updateLocaleSpecifics(Locale currentLocale) {
        dateFormat = DateFormat.getDateInstance(DateFormat.SHORT, currentLocale);
        timeFormat = DateFormat.getTimeInstance(DateFormat.SHORT, currentLocale);
    }

    // There objects are used to format dates and numbers
    private DateFormat dateFormat;
    private DateFormat timeFormat;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JComboBox<String> localeCombobox;
    private javax.swing.JLabel timeLabel;
    private TransparencyPanel transparencyPanel1;
    // End of variables declaration//GEN-END:variables
}
