
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Hafsa Umar
 */
public class Information extends javax.swing.JFrame {

    /**
     * Creates new form Information
     */
    public Information() {
        initComponents();
    }
    private List<Person> people;
    private int peopleSize;
    private int current;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fnameTextbox = new javax.swing.JTextField();
        lnameTextbox = new javax.swing.JTextField();
        btownTextbox = new javax.swing.JTextField();
        byearTextbox = new javax.swing.JTextField();
        fnameEditButton = new javax.swing.JButton();
        lnameEditButton = new javax.swing.JButton();
        btownEditButton = new javax.swing.JButton();
        byearEditButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ldataMenu = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        nextMenu = new javax.swing.JMenuItem();
        prevMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("First Name");

        jLabel2.setText("Last Name");

        jLabel3.setText("Birth Town");

        jLabel4.setText("Birth Year");

        fnameTextbox.setEditable(false);
        fnameTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameTextboxActionPerformed(evt);
            }
        });

        lnameTextbox.setEditable(false);

        btownTextbox.setEditable(false);
        btownTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btownTextboxActionPerformed(evt);
            }
        });

        byearTextbox.setEditable(false);

        fnameEditButton.setText("Edit");
        fnameEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameEditButtonActionPerformed(evt);
            }
        });

        lnameEditButton.setText("Edit");
        lnameEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameEditButtonActionPerformed(evt);
            }
        });

        btownEditButton.setText("Edit");
        btownEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btownEditButtonActionPerformed(evt);
            }
        });

        byearEditButton.setText("Edit");
        byearEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byearEditButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        ldataMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        ldataMenu.setText("Load Data");
        ldataMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ldataMenuActionPerformed(evt);
            }
        });
        jMenu1.add(ldataMenu);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Load Population");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("View");

        nextMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        nextMenu.setText("Next");
        nextMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextMenuActionPerformed(evt);
            }
        });
        jMenu2.add(nextMenu);

        prevMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        prevMenu.setText("Previous");
        prevMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevMenuActionPerformed(evt);
            }
        });
        jMenu2.add(prevMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fnameTextbox)
                    .addComponent(lnameTextbox)
                    .addComponent(btownTextbox)
                    .addComponent(byearTextbox, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lnameEditButton)
                    .addComponent(fnameEditButton)
                    .addComponent(btownEditButton)
                    .addComponent(byearEditButton))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fnameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnameEditButton))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lnameTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnameEditButton))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btownTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btownEditButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(byearTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(byearEditButton))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnameTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameTextboxActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_fnameTextboxActionPerformed

    private void btownTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btownTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btownTextboxActionPerformed

    private void ldataMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ldataMenuActionPerformed
        
        initializeFileData();
        displayNextRowData();
    }//GEN-LAST:event_ldataMenuActionPerformed

    private void initializeFileData(){
        String fileName = "people.txt";
        people = Person.loadPersons(fileName);
        System.out.println("Loading persons from file " + fileName);
        System.out.println(people.size());
        people.forEach((p) -> {
            System.out.println(p);
        });
        peopleSize = people.size();
        current = -1;
    }
    private void displayNextRowData(){
        if (current != (peopleSize-1)) {
            current++;
            fnameTextbox.setText(people.get(current).getFirstName());
            lnameTextbox.setText(people.get(current).getLastName());
            byearTextbox.setText(String.valueOf(people.get(current).getBirthYear()));
            btownTextbox.setText(people.get(current).getBirthTown());         
        } else {
            JOptionPane.showMessageDialog(this, "No more people, Load Again to Continue", "Stop", JOptionPane.CANCEL_OPTION);
        }
    }
    
    private void displayPreviousRowData(){
        if (current > 0 && current < peopleSize) {
            current--;
            fnameTextbox.setText(people.get(current).getFirstName());
            lnameTextbox.setText(people.get(current).getLastName());
            byearTextbox.setText(String.valueOf(people.get(current).getBirthYear()));
            btownTextbox.setText(people.get(current).getBirthTown());
        } else {
            JOptionPane.showMessageDialog(this, "No more people, Load Again to Continue", "Stop", JOptionPane.CANCEL_OPTION);
        }
    }
    
    private void nextMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextMenuActionPerformed
        displayNextRowData();
    }//GEN-LAST:event_nextMenuActionPerformed

    
    private void prevMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevMenuActionPerformed
        displayPreviousRowData();
    }//GEN-LAST:event_prevMenuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int r = JOptionPane.showConfirmDialog(this, "Are you sure?", "Wait!!", JOptionPane.OK_CANCEL_OPTION);
        if (r == JOptionPane.OK_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void fnameEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameEditButtonActionPerformed
        String firstName = JOptionPane.showInputDialog(this, "Please input First Name", "Edit", JOptionPane.OK_CANCEL_OPTION);
        people.get(current).setFirstName(firstName);
        fnameTextbox.setText(firstName);
    }//GEN-LAST:event_fnameEditButtonActionPerformed

    private void lnameEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameEditButtonActionPerformed
        String lastName = JOptionPane.showInputDialog(this, "Please input Last Name", "Edit", JOptionPane.OK_CANCEL_OPTION);
        people.get(current).setLastName(lastName);
        lnameTextbox.setText(lastName);
    }//GEN-LAST:event_lnameEditButtonActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Population pop = new Population("Canada");
        people = new LinkedList<Person>();
        for (int i = 0; i < 6; i++){
            people.add(pop.nextPerson());
        }
        peopleSize = people.size();
        current = -1;
        displayNextRowData();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btownEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btownEditButtonActionPerformed
        String birthTown = JOptionPane.showInputDialog(this, "Please input Birth Town", "Edit", JOptionPane.OK_CANCEL_OPTION);
        people.get(current).setBirthTown(birthTown);
        btownTextbox.setText(birthTown);
    }//GEN-LAST:event_btownEditButtonActionPerformed

    private void byearEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byearEditButtonActionPerformed
       try{
        String birthYear = JOptionPane.showInputDialog(this, "Please input Birth Year", "Edit", JOptionPane.OK_CANCEL_OPTION);
        people.get(current).setBirthYear(Integer.parseInt(birthYear));
        byearTextbox.setText(birthYear);
       }catch(NumberFormatException ex){
           JOptionPane.showMessageDialog(this, "Please Enter valid Year", "Error", JOptionPane.OK_OPTION);
       }
    }//GEN-LAST:event_byearEditButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       int r = JOptionPane.showConfirmDialog(this, "Are you sure?", "Wait!!", JOptionPane.OK_CANCEL_OPTION);
        if (r == JOptionPane.OK_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Information().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btownEditButton;
    private javax.swing.JTextField btownTextbox;
    private javax.swing.JButton byearEditButton;
    private javax.swing.JTextField byearTextbox;
    private javax.swing.JButton fnameEditButton;
    private javax.swing.JTextField fnameTextbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem ldataMenu;
    private javax.swing.JButton lnameEditButton;
    private javax.swing.JTextField lnameTextbox;
    private javax.swing.JMenuItem nextMenu;
    private javax.swing.JMenuItem prevMenu;
    // End of variables declaration//GEN-END:variables
}
